In [11]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression, LinearRegression

In [26]:
spotify = pd.read_csv('data/spotifydf.csv')
spotify = spotify[[
    'acousticness',
    'danceability',
    'duration_ms',
    'energy',
    'explicit',
    'instrumentalness',
    'key',
    'liveness',
    'loudness',
    'mode',
    'popularity',
    'speechiness',
    'tempo',
    'valence',
    'year'
]]
spotify.loc[spotify['popularity'] < 70, 'popularity'] = 0
spotify.loc[spotify['popularity'] >= 70, 'popularity'] = 1
spotify.head()

acousticness  danceability  duration_ms  energy  explicit  \
0         0.995         0.708       158648  0.1950         0   
1         0.994         0.379       282133  0.0135         0   
2         0.604         0.749       104300  0.2200         0   
3         0.995         0.781       180760  0.1300         0   
4         0.990         0.210       687733  0.2040         0   

   instrumentalness  key  liveness  loudness  mode  popularity  speechiness  \
0             0.563   10    0.1510   -12.428     1           0       0.0506   
1             0.901    8    0.0763   -28.454     1           0       0.0462   
2             0.000    5    0.1190   -19.924     0           0       0.9290   
3             0.887    1    0.1110   -14.734     0           0       0.0926   
4             0.908   11    0.0980   -16.829     1           0       0.0424   

     tempo  valence  year  
0  118.469   0.7790  1928  
1   83.972   0.0767  1928  
2  107.177   0.8800  1928  
3  108.003   0.7200  1928  
4   62.149   0.0693  1928

In [27]:
def spotify_logistic_regression(Xfeatures, spotify_df=spotify):
    X = spotify_df[Xfeatures]
    Y = spotify_df['popularity']
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
    model = LogisticRegression().fit(X_train,Y_train)
    Y_hat = model.predict(X_test)
    return Y_hat,Y_test

In [62]:
def logistic_regression_plot(columns, spotify_df=spotify):
    y_hat,y_reals = spotify_logistic_regression(columns,spotify_df=spotify_df)
    print("Accuracy: {}".format(accuracy_score(y_hat,y_reals)))
    print(confusion_matrix(y_hat,y_reals))

In [63]:
logistic_regression_plot([
    'acousticness',
    'danceability',
    'duration_ms',
    'energy',
    'explicit',
    'instrumentalness',
    'key',
    'liveness',
    'loudness',
    'mode',
    'speechiness',
    'tempo',
    'valence',
#     'year'
])

Accuracy: 0.972720852215879
[[33055   926]
 [    1     0]]


In [79]:
logistic_regression_plot([
    'acousticness',
    'danceability',
    'duration_ms',
    'energy',
    'explicit',
    'instrumentalness',
    'key',
    'liveness',
    'loudness',
    'mode',
    'speechiness',
    'tempo',
    'valence',
    'year'
], spotify_df=spotify[spotify['year'] < 1990])

Accuracy: 0.9955198374209043
[[21554    97]
 [    0     0]]


In [89]:
logistic_regression_plot([
#     'acousticness',
    'danceability',
#     'duration_ms',
    'energy',
    'explicit',
#     'instrumentalness',
#     'key',
    'liveness',
#     'loudness',
#     'mode',
    'speechiness',
    'tempo',
#     'valence',
#     'year'
], spotify_df=spotify[spotify['year'] > 2006])

Accuracy: 0.8765365148228489
[[4849  683]
 [   0    0]]
